homeassistant:
  enabled: true
advanced:
  network_key:
    - 95
    - 79
    - 162
    - 132
    - 65
    - 46
    - 110
    - 194
    - 96
    - 211
    - 192
    - 87
    - 41
    - 63
    - 3
    - 177
  pan_id: 36961
  ext_pan_id:
    - 110
    - 244
    - 2
    - 96
    - 197
    - 124
    - 20
    - 80
  log_level: debug
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: mqtt
  base_topic: zigbee2mqtt
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_4a3cf6fa99dbed11a440e62d62c613ac-if00-port0
  adapter: ember
device_options: {}
devices:
  '0x30fb10fffe4c12d6':
    friendly_name: IKEA Tradfri Switch 1
    icon: device_icons/f1504ae638f983567e4384447325f67a.png
  '0x30fb10fffe4c1e7d':
    friendly_name: IKEA Tradfri Switch 2
    icon: device_icons/f1504ae638f983567e4384447325f67a.png
  '0x842712fffedb8ddb':
    friendly_name: IKEA Tradfri Mittled Driver
    icon: device_icons/411c97850db9a9d71a184c23fa36ca82.png
  '0xa4c13800ab3b1cc6':
    friendly_name: Paulmann Spring Bulb 29159
  '0xa4c138247a1a948b':
    friendly_name: Tuya Connected Outlet
    icon: device_icons/08a9016bbc0657cf5f581ae9c19c31a5.png
  '0xd44867fffeff5bc8':
    friendly_name: IKEA Rodret Switch 1
    icon: device_icons/36c972f318c6801ebb07c8b1dde874df.png
  '0x6cfd22fffe610d7c':
    friendly_name: IKEA Vallhorn Detector 1
    icon: device_icons/27dc30501ab148ff5b7c68982359344c.png
  '0x8c8b48fffe18b6d8':
    friendly_name: IKEA Rodret Switch 2
version: 4
